### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by pepa65**
Fixed typo (\m) and added /tmp with proper permissions (otherwise non-root can't write to /tmp as it gets created with too restrictive permissions).

### CODE REVIEW

**Comment by fsmithred** [comment]
Thanks. I fixed the typo.

Why do you need to make /tmp? That should get copied with the same
permissions as on the host/build system's /tmp. That's what I'm seeing
here in $work_dir/myfs/ and in my isos.

fsr

**Comment by pepa65** [comment]
Could it be because I use /tmp as the iso directory (and /tmp/refracta as the work directory)??
In any case, I have found that the /tmp directory always had insufficient permissions, and this caused problems when logging in through slim as it creates keyboard files in /tmp.

**Comment by fsmithred** [comment]
Maybe. Are you using /tmp for $snapshot_dir or for $iso_dir? I think
there's something broken with using a custom $iso_dir, but I haven't
looked at it closely.

**Comment by pepa65** [comment]
```
snapshot_dir="/tmp"
work_dir="/tmp/refracta"
```
I remember a few years ago I used a similar script that also used the home directory for the results and I found that unexpected, and since the config option was offered, I decided to change it.

**Comment by fsmithred** [comment]
That shouldn't be a problem. If the snapshot_dir exists, the script just
uses it. If it doesn't exist, it creates it and does a chmod 777 on it.
The original version of refractasnapshot used /tmp/snapshot and /tmp/work.
I moved them to /home because that's often on the biggest partition.

If you run the script from command-line with the -d option, you'll get a
debug log with every action recorded. That might give a hint at what's
going on. Check permissions on /tmp on the host system if you haven't
already done so.

run:
  refractasnapshot -d
or
  refractasnapshot-gui -d

**Comment by pepa65** [comment]
OK I'll try with the debug to see what's happening. The host is a fairly fresh Devuan install with /tmp permissions 777.

**Comment by pepa65** [comment]
In my case, /tmp gets excluded in the rsync command.

**Comment by fsmithred** [comment]
It should actually be /tmp/* in the excludes file. Try setting the
snapshot dir /tmp/snapshot. Or put it somewhere other than /tmp so you
don't lose your iso if you reboot. $work_dir and $snapshot_dir get
excluded wherever you put them.

**Comment by pepa65** [comment]
I guess the assumption is that `snapshot_dir`and `work_dir` should be single-purpose directories, because they will be excluded from rsync. I'll put them in /root/... myself. Yes, you're right about /tmp by default not surviving reboots, that's not a handy choice if I'm not OK with losing the contents..! Thanks for your help, and thanks for all your work!

**Pull request closed without merging**
